name: i18n_omatic
description: >
  i18n-o-matic makes translations easier in Flutter apps 
  with automatic search for translatable strings in the source code.

homepage: https://github.com/jctophefabre/i18n_omatic
issue_tracker: https://github.com/jctophefabre/i18n_omatic/issues

version: 0.2.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  args: ^1.6.0
  glob: ^1.2.0
  yaml: ^2.2.1
  path: ^1.7.0

dev_dependencies:
  test: ^1.15.7
  pedantic: ^1.9.0